<?php

namespace App\Console\Commands;

use App\Enums\MonitoringStatus;
use App\Services\Production\RecoveryEvidenceLedger;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;
use InvalidArgumentException;
use Throwable;

final class RecordVerifiedBackupHeartbeat extends Command
{
    protected $signature = 'monitoring:backup-verified
        {--operation-id= : Stable opaque ID; retries must reuse it}
        {--backup-id= : Opaque identifier generated by the backup process}
        {--provider= : Managed database/backup provider identifier}
        {--source-snapshot-at= : Backup source timestamp in ISO-8601}
        {--recovery-point-at= : Latest restorable timestamp in ISO-8601}
        {--completed-at= : Backup verification completion in ISO-8601}
        {--immutable-until= : Provider object-lock expiry in ISO-8601}
        {--object-lock-mode= : Verified provider object-lock mode}
        {--size-bytes= : Verified archive size in bytes}
        {--checksum-sha256= : SHA-256 checksum of the verified archive}
        {--archive-readable : Archive was opened/read by the verifier}
        {--checksum-verified : Full checksum comparison succeeded}
        {--encrypted : Backup encryption was verified}
        {--offsite : Backup resides outside the primary database boundary}
        {--cross-account : Backup resides in an independently controlled account}
        {--cross-region : Backup copy exists outside the primary region}';

    protected $description = 'Append signed evidence after an immutable off-site backup passes verification';

    public function handle(RecoveryEvidenceLedger $ledger): int
    {
        if (! (bool) config('monitoring.backup.enabled', false)
            || ! (bool) config('disaster_recovery.backup.enabled', false)) {
            if (! $this->option('quiet')) {
                $this->components->error('Verified immutable backup monitoring is disabled.');
            }

            return self::INVALID;
        }

        try {
            $backupId = trim((string) $this->option('backup-id'));
            $operationId = trim((string) $this->option('operation-id')) ?: $backupId;
            $evidence = $ledger->recordBackup([
                'operation_id' => $operationId,
                'backup_id' => $backupId,
                'provider' => $this->option('provider'),
                'source_snapshot_at' => $this->option('source-snapshot-at'),
                'recovery_point_at' => $this->option('recovery-point-at'),
                'completed_at' => $this->option('completed-at'),
                'immutable_until' => $this->option('immutable-until'),
                'object_lock_mode' => $this->option('object-lock-mode'),
                'size_bytes' => $this->option('size-bytes'),
                'checksum_sha256' => $this->option('checksum-sha256'),
                'archive_readable' => (bool) $this->option('archive-readable'),
                'checksum_verified' => (bool) $this->option('checksum-verified'),
                'encrypted' => (bool) $this->option('encrypted'),
                'offsite' => (bool) $this->option('offsite'),
                'cross_account' => (bool) $this->option('cross-account'),
                'cross_region' => (bool) $this->option('cross-region'),
            ]);

            if (! $this->option('quiet')) {
                $this->components->info(
                    "Verified immutable backup evidence #{$evidence->sequence} recorded.",
                );
            }

            return $evidence->status === MonitoringStatus::Operational->value
                ? self::SUCCESS
                : self::FAILURE;
        } catch (InvalidArgumentException $exception) {
            if (! $this->option('quiet')) {
                $this->components->error($exception->getMessage());
            }

            return self::INVALID;
        } catch (Throwable $exception) {
            Log::error('monitoring.backup_evidence_failed', [
                'failure_class' => $exception::class,
            ]);

            if (! $this->option('quiet')) {
                $this->components->error('Verified backup evidence could not be recorded.');
            }

            return self::FAILURE;
        }
    }
}
